### ISSUE TITLE
Bring in OsmApiClient

### ISSUE THREAD

**Issue by HarelM** [OsmSharp/io-api#2]
Hi @xivk,

I see that this repo isn't very maintained.
@blackboxlogic and I are working on the following project together which I think is similar:
[OsmApiClient](https://github.com/blackboxlogic/OsmApiClient)
I think it might be beneficial to bring it in under the umbrella of OsmSharp, what do you think?
I'm using it in production for a while now which great success.
Please let me know how you would like to proceed with this.
Generally speaking, the maintenance of this will still be with @blackboxlogic and myself so besides the initial setup I don't see any work from you end.

I'm a maintainer in this organization, but I don't have the permissions to create a new repo or assign the relevant permissions in order to add secrets for example to publish nuget packages (I think).

**Comment by xivk** [comment]
Ok, I'll look into how to do this best. I very much welcome these contributions...

Do you mind enabling 2FA on github on your account @HarelM ?

**Comment by HarelM** [comment]
I just did, let me know if you need anything else.

**Comment by HarelM** [comment]
@xivk any updates on this?

**Comment by xivk** [comment]
I wasn't comfortable adding you as full admin to the organization apologies for that! I have given you full access to this repo though, so can you check if you have everything you need? 

If in the future you want to collaborate further and get greater say over OsmSharp maintenance in general, something I would welcome, then I suggest we first have a live conversation to discuss.

**Comment by HarelM** [comment]
Great! Thanks!
If that's fine with you, I'll replace the entire code here with the above linked repository and add the relevant CI and Nuget Keys to allow publishing of this package.
If you prefer the package to have a different name let us know.
The current name is `OsmApiClient`, thinking about it, it might be better to rename it to `OsmSharp.ClientAPI` or `OsmSharp.APIClinet`, or a different name, or even replace the exsiting nuget package: `OsmSharp.API`, IDK...
Adding @blackboxlogic to this thread, and I'll be adding him as an admin to this repo as well as we have maintained the client together.

**Comment by blackboxlogic** [comment]
@xivk thanks for your support moving the code into your org. I wonder if eventually the nugget package should also be published with the same author/branding as your other osm nugget packages.

@HarelM thanks for doing this. Once it's moved I will make sure everything points to this new repo (osm wiki, nugget link to source, etc).

Regarding name, the [API](https://wiki.openstreetmap.org/wiki/API) seems to be _formally_ named "Editing API". I'm not picky, but I'd suggest including that to specify which API this supports. Or maybe leave it off if we think this client might support other APIs later.

**Comment by HarelM** [comment]
There is actually an old package named OsmSharp.API, @xivk can you add us as maintainers of this package in nuget or add a secret to this repo so we can publish it?
I think we should update this old package and deprecate the current one.
I hope to have time later tonight to bring in all the code, but feel free to beat me to it...

**Comment by blackboxlogic** [comment]
It's not clear to me if this existing repo was intended to be an implementation of the API client or service. Looking through the read me and code doesn't answer that for me either. Looking at the description on the nuget package makes this seem like the service: "OsmSharp.API is a clone of the OSM-API".

So... We might be entirely changing what this repo is, which could be fine, but what's not fine is that the name will still be super confusing between the two. I think a repo can be renamed, I don't think a nuget package can.

**Comment by xivk** [comment]
This was intended to be an clone of the API itself so not a client but feel free to repurpose the project... 

@HarelM we can do a live chat sometime beginning of next year, I'm just too busy trying to finish things by the end of the year.

I can give you access to nuget but I would recommend create a package with another name, making it clear it is a client. Perhaps `OsmSharp.API.Client`?

**Comment by HarelM** [comment]
Beginning of next year works for me, I've sent you a mail, so you know how to reach me.
We can create another repo if needed, but I'm not sure I understand what other implementation is possible beside the client, but I might be missing an obvious thing here.
The name osmsharp.api.client sounds good to me, I'm just not sure what the other package would mean and why it's there, so this can be confusing as well...
In any case, the problem here is not the code :-)

**Comment by blackboxlogic** [comment]
@HarelM the API "service" is code running on a server that receives and responds to these requests, probably sitting on top of an osm database. I assume the reason that didn't come to you is because "why would anyone want to re write that in c#", but I think OsmSharp has a vision of supporting the entire OSM ecosystem in c# (or whatever portion is feasible).

**Comment by HarelM** [comment]
Ahh, I see.

**Comment by HarelM** [comment]
I've opened the main PR for this.
I've opened some basic issues to solve after this gets merged to create what I see as an MVP for this project.
Feel free to enhance :-)

**Comment by xivk** [comment]
Writing this API clone was just something I need for my company [ANYWAYS](https://www.anyways.eu/) where we use OSM data and the iD editor but not the original OSM API setup but our own. 

But the longer this project lasted the less sense it made to maintain this under this organization and this code just because stale.
