### ISSUE TITLE
Align naming to prepare for publishing

### ISSUE THREAD

**Issue by HarelM** [OsmSharp/io-api#6]
@xvik @blackboxlogic Please let me know what should be the next step in terms of package rename, repo rename, etc.
I'm fine with whatever works for you guys.
The only thing that's currently missing is adding a secret to this repo to allow publishing a package (and testing it obviously).
Once we select a name (and a namespace) I can replace it everywhere and publish a package.
Waiting for your input here in order to proceed.

**Comment by xivk** [comment]
Whatever package name you think is best is fine for me. Feel free to reuse OsmSharp.API or something like that.

**Comment by xivk** [comment]
Do I add a secret to publish packages under the OsmSharp account?

**Comment by HarelM** [comment]
I now see that there are two organizational secrects already, so I guess you don't need to do anything ATM, I'll test things out in the coming days and report if everything is working as expected.
Thanks!!

**Comment by HarelM** [comment]
Current name is `OsmSharp.IO.API`, there was a different name in the old repo, but I don't remember fixing this, weird.
I'm good with that name.
I'm also good with `OsmSharp.API.Client` as was suggested elsewhere.
@blackboxlogic which one do you prefer?
Do we want to change the repo name as well to be `API-Client` or `IO-API` to match the package name under the OsmSharp org?
I'm also fine with keeping it with the current name, but changing it would be better I believe.

**Comment by blackboxlogic** [comment]
@HarelM 

Re: "Current name is..."
Which _name_? Repo, project, namespace, package?

I'd rather have `OsmSharp.IO.API` for all names, where possible.

We had talked about publishing this as a new nuget package. I wonder if there is a way to gracefully help existing project's which refer to the old nuget package find the new package. If not, what do you think of just continuing to update the existing nuget package and giving xivk publish permissions on nuget.org (instead of making a new package)?

I just noticed [this project](https://github.com/OsmSharp/osm-api-client) from the distant past, which should probably be deleted. I tried to start this project under OsmSharp, but moved it under my github user, I think when I ran into permissions issues publishing the nuget package.

**Comment by HarelM** [comment]
I wouldn't like to maintain it twice. @blackboxlogic If this is something you would like to do feel free.
I think the current nuget name is not good as it doesn't have the same namespace, so I think a new package name is needed, it should also has the same icon as the rest of the osmsharp packages to indicate that this is more "official".
I think we can change the readme in your repo to link to the new repo.
The following is the documentation about deprecation which I believe we should follow once we deprecate the old package:
https://learn.microsoft.com/en-us/nuget/nuget-org/deprecate-packages

@blackboxlogic what do you think this repo name should be then? `io-api`?
@xivk can you delete [osm-api-client](https://github.com/OsmSharp/osm-api-client) repo please?

Happy new year guys!! :-)

Once we agree on this repo name and have it renamed I guess we change change the link in the nuget to point to it and have it published, hopefully...

**Comment by blackboxlogic** [comment]
I retract my suggestion to keep the old nuget package alive since there's a way to deprecate it (thanks for find that). Yes, I think `io-api` fits bets as repo name.

**Comment by HarelM** [comment]
I've renamed the repo, and changed the csproj. Is there anything else missing?

**Comment by blackboxlogic** [comment]
Nothing else I can think of. I think we're ready to publish the nuget package under the new org? Probably start at version 1.0.0

**Comment by HarelM** [comment]
Released, with icon and readme in nuget.
https://www.nuget.org/packages/OsmSharp.IO.API

Enjoy!

**Comment by HarelM** [comment]
P.S. every commit to main is creating a new package, so there's a need to update the version in those 3 places before merging/committing.

**Comment by HarelM** [comment]
For some reason the icon in Nuget doesn't work, feel free to try and fix this...
Setting `<PackageIconUrl>https://www.osmsharp.com/logos/osmsharp_logo64.png</PackageIconUrl>` throws a deprecation warning on build, and `<Icon>, `<IconUrl>` don't work for me, not sure why.

**Comment by blackboxlogic** [comment]
"every commit creates a package" is by-design lazy feature. You can commit to main without incrementing the nuget version and it won't make a new package (it will try and fail, reporting a failed build).
There's probably a better way to manage that, and I wouldn't mind if someone changed it, but this is good enough for me for now.

**Comment by xivk** [comment]
I usually make it so that the build doesn't fail, it's an option in nuget push. Only when the version number is bumped a new package is created.

**Comment by blackboxlogic** [comment]
I found that option and used it for the upload of symbols. Between "get false build errors when I make a change and intentionally don't bump the version" and "don't get any notification when I meant to bump the version and forgot to" I chose the first. But feel free to change it to suit you.
